name: Check changes to master

on :
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  lint_ci:
    name: Lint CI
    uses: ./.github/workflows/lint_ci.yaml
  
  lint_css:
    name: Lint CSS
    uses: ./.github/workflows/lint_css.yaml

  lint_html:
    name: Lint HTML code
    uses: ./.github/workflows/lint_html.yaml

  lint_javascript:
    name: Lint JavaScript code
    uses: ./.github/workflows/lint_javascript.yaml

  check_markdown:
    name: Check Markdown code
    uses: ./.github/workflows/check_markdown.yaml

  build_website:
    name: Build website
    needs:
      - lint_ci
      - lint_css
      - lint_html
      # - lint_javascript # FOR NOW UNTIL DORNY PATHS FILTER IS IMPLEMENTED
      - check_markdown
    uses: ./.github/workflows/build.yaml

  deploy_website:
    name: Deploy website
    needs:
      - lint_ci
      - lint_css
      - lint_html
      - lint_javascript
      - check_markdown
      - build_website
    if: ${{ github.ref == 'refs/heads/master' }}
    permissions:
      contents: write
    uses: ./.github/workflows/deploy.yaml
