name: Check HTML

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint_html:
    name: Lint HTML code
    runs-on: ubuntu-latest
    steps:
      - name: Install html-validate
        run: |
          npm install -g html-validate
      - name: Run html-validate
        run: |
          for file in **/*.html; do
            html-validate  \
              --preset recommended \
              --rule wcag/h30:off \
              "${file}" || {
              echo "ERROR: HTML validation failed on ${file}"
              cat "${file}"
              exit 1
            }
          done
