name: Lint CSS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint_css:
    name: Lint CSS code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Create package lock
        run: touch package-lock.json
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
      - name: Install CSS linters
        run: |
          npm install -g csslint stylelint stylelint-config-standard
      - name: Run csslint
        run: |
          csslint \
            --ignore=box-sizing \
            --ignore=known-properties \
            src/style.css
      - name: Run Stylelint
        run: |
          stylelint \
            src/style.css \
            --config config/stylelint.json
