name: Lint JavaScript

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint_javascript:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Create package lock
        run: touch package-lock.json
      - name: Install eslint
        run: npm install -g eslint
      - name: Lint JavaScript
        run: eslint .
