name: Renovate

on:
  schedule:
    - cron: "13 05 * * *"
  workflow_dispatch:

env:
  RENOVATE_CONFIG_PATH: 'config/renovate.json'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@v46.1.8
        with:
          configurationFile: ${{ env.RENOVATE_CONFIG_PATH }}
          token: ${{ secrets.RENOVATE_TOKEN }}
